cache_resources:
  - label: red
    redis:
      url: redis://redis:6379

input:
  label: "ftp_input"
  sftp:
    address: "X.X.X.X:22"
    credentials:
      username: "XXXX"
      password: "XXXX"    
    paths:
      - "./Protei/3*.log.gz"
    scanner:
      decompress:
        algorithm: "gzip"
        into:
          csv:
            custom_delimiter: ";"
            parse_header_row: false
            lazy_quotes: false
            continue_on_error: false        
    auto_replay_nacks: true
    delete_on_finish: false
    watcher:
      enabled: true
      minimum_age: 1m
      poll_interval: 1s
      cache: red
pipeline:
  processors:
    - bloblang: |
        root = {
          "ETL_TIME": now().ts_format("2006-01-02 15:04:05.999999", "Asia/Tehran"),
          "Col_1": this.0,
          "Col_2": this.1,
          "Col_3": this.2,
          "Col_4": this.3,
          "Col_5": this.4,
          "Col_6": this.5,
          "Col_7": this.6
        }
output:
  broker:
    pattern: fan_out
    outputs:
      - kafka:
          addresses:
            - redpanda:9092
          topic: sms
          max_in_flight: 5
          client_id: redpanda_connect
          compression: snappy



